### PR TITLE
New group selection input; gps button; Fixed error in which the group…

### PR DESCRIPTION
**Pull request by DylanCarbone**
… and species selection were reset with the selection of a new species group; Made rasters appear more tidy by replacing 0 occurence predictions with NA; Fixed an issue in which the species group and species selection picker inputs would overlap.

### CODE REVIEW

**Comment by DylanCarbone** [comment]
Hi @Nithador,

When you have the time, could you please review my changes and let me know if you have any issues. Thanks

**Comment by Nithador** [comment]
Hi @DylanCarbone in general, I think it looks good, but I wonder about the `as.character()` around the `sliderTextInput()` functions. Should this be  `shiny` package `tagList()` function? I think that would be more proper way. Can You try that out?

@csckata there is a `tags$head` added at line 25 adding style for dropdown-menu, could You check it out, and move it to the scss style. I would prefer having it there with as a child style for the ces_rp_biodiversity.R page than having it in a header.

**Comment by DylanCarbone** [comment]
Thanks @Nithador,

I switched to using tagList() over as.character() and it works. This pull request should be updated with the code. Also, by grouping the group and species selector into a single tagList(), I was able to remove the initial issue of selector input overlap. I have therefore removed the tags$head as it is no longer necessary. I also added the waiter$show() and waiter$hide() calls that I forgot to include in the original pull request.

**Comment by Nithador** [comment]
I merged this and it works fine on my pc, however on Shinyproxy it breaks quite a lot. I will try to look into this. But, if You have time take a look at app.biodt.eu.

**Comment by DylanCarbone** [comment]
Hmm, it looks like the shinyWidgets functions are not working correctly in shinyproxy. I'll look into alternatives.

**Comment by Nithador** [comment]
Please do not. I want to have shinyWidgets there :). We must figure out how to make it work with our shinyproxy. I will look into settings and what could trigger this.

Ing. Tomáš Martinovič, Ph.D.
Senior researcher

e-mail: ***@***.***
phone: +420 596 999 580

IT4Innovations national supercomputing center, VSB-TUO
Studentská 6231/1b, 708 00 Ostrava-Poruba, Czech Republic

**Pull request merged**
